language: ruby

services:
  - docker

before_install:
  - docker pull amazoncorretto:11

script:
  - echo $DOCKER_HOST
  - docker info
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source -v artifact_volume:/artifact_volume -e GPR_USERNAME=$GPR_USERNAME -e GPR_PASSWORD=$GPR_PASSWORD amazoncorretto:11 /bin/sh -c "cd /source ; ./gradlew clean build -PciBuild -x test"

after_script:
  - $TRAVIS_BUILD_DIR/gradlew bootBuildImage
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joelin/einvoice-service:latest